[package]
name = "pdb"
version = "0.1.0"
authors = ["jrieck <jack.rieck@sendgrid.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sgx-isa = { version = "0.3", features = ["sgxstd"] }
rand = "0.7"